CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE items (
  item_id SERIAL PRIMARY KEY,
  user_id INT4 REFERENCES users(id) ON DELETE CASCADE,
  text VARCHAR(2000)
);